# Generated by Django 5.1.4 on 2024-12-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterboxbackend', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='songId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='userId',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
