# Generated by Django 5.1.4 on 2024-12-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterboxbackend', '0006_alter_saved_songid_alter_saved_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='songId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betterboxbackend.song'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betterboxbackend.user'),
        ),
    ]
